package pojo;
// Generated Apr 14, 2015 12:45:49 AM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
//import org.hibernate.mapping.Column;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;

/**
 * Student generated by hbm2java
 */
public class Student  implements java.io.Serializable {

@Column(columnDefinition = "serial")
  //@Column(columnDefinition = "serial")
    private BigDecimal examRollNo;
     private BigDecimal classRollNo;
     private String name;
     private String regNo;
     private String emailId;
     private String paymentId;
     private String subjects;

    public Student() {
    }

	
    public Student(BigDecimal examRollNo) {
        this.examRollNo = examRollNo;
    }
    public Student(BigDecimal examRollNo, BigDecimal classRollNo, String name, String regNo, String emailId, String paymentId, String subjects) {
       this.examRollNo = examRollNo;
       this.classRollNo = classRollNo;
       this.name = name;
       this.regNo = regNo;
       this.emailId = emailId;
       this.paymentId = paymentId;
       this.subjects = subjects;
    }
   
    public BigDecimal getExamRollNo() {
        return this.examRollNo;
    }
    
    public void setExamRollNo(BigDecimal examRollNo) {
        this.examRollNo = examRollNo;
    }
    public BigDecimal getClassRollNo() {
        return this.classRollNo;
    }
    
    public void setClassRollNo(BigDecimal classRollNo) {
        this.classRollNo = classRollNo;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRegNo() {
        return this.regNo;
    }
    
    public void setRegNo(String regNo) {
        this.regNo = regNo;
    }
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }
    public String getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(String paymentId) {
        this.paymentId = paymentId;
    }
    public String getSubjects() {
        return this.subjects;
    }
    
    public void setSubjects(String subjects) {
        this.subjects = subjects;
    }




}


